owner: lucasenlucas
repo: codeblocks-status

sites:
  - name: codeblocks.nl
    url: https://www.codeblocks.nl
  - name: codeblocks paneel
    url: https://login.codeblocks.nl
  - name: codeblocks API
    url: https://codeblocks-app.web.app
  - name: CDN
    url: https://cdn.codeblocks.nl

status-website:
  cname: status.codeblocks.nl
  logoUrl: https://codeblocks.nl/cdn-homepage/codeblocks_logo_tekst_zwart_achtergrond_transparant.png
  name: Codeblocks Status
  introTitle: Codeblocks status
  introMessage: We monitoren live of alle systemen werken. Problemen? Bekijk hier de status.
  navbar:
    - title: Status
      href: /
    - title: Mail
      href: mailto:info@codeblocks.nl
